plugins {
    id("net.neoforged.moddev.legacyforge") version "2.0.91"
    id("com.diffplug.spotless") version "8.1.0"
    id("me.modmuss50.mod-publish-plugin") version "1.0.0"
}

group = "me.ramidzkh"
version = System.getenv("APPMEK_VERSION") ?: "0.0.0"

repositories {
    maven {
        name = "Modmaven"
        url = uri("https://modmaven.dev/")

        content {
            includeGroup("appeng")
            includeGroup("mekanism")
        }
    }

    maven {
        name = "Jared maven"
        url = uri("https://maven.blamejared.com/")

        content {
            includeGroup("mezz.jei")
        }
    }

    maven {
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }

    maven {
        url "https://maven.terraformersmc.com"
        content {
            includeGroup "dev.emi"
        }
    }

    maven {
        name = "Local"
        url = file("libs").toURI()
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

obfuscation {
    createRemappingConfiguration(configurations.localRuntime)
}

dependencies {
    compileOnly("org.jetbrains:annotations:26.0.2-1")

    // We depend on many AE2 internals, such as using their basic cell drive, thus not using classifier = "api"
    modImplementation("appeng:appliedenergistics2-forge:${ae2_version}")
    modRuntimeOnly("org.appliedenergistics:guideme:${guideme_version}")

    modCompileOnly("mekanism:Mekanism:${minecraft_version}-${mekanism_version}:api")
    modRuntimeOnly("mekanism:Mekanism:${minecraft_version}-${mekanism_version}:all")

    modCompileOnly("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    modCompileOnly("dev.emi:emi-forge:${emi_version}")

    modRuntimeOnly("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")
    modRuntimeOnly("dev.emi:emi-forge:${emi_version}")

    modImplementation("curse.maven:jade-324717:${jade_id}")
}

sourceSets {
    main {
        resources {
            srcDir("src/generated/resources")
        }
    }
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

////////////////////
// Forge/Minecraft
legacyForge {
    version = "${project.minecraft_version}-${project.forge_version}"

    runs {
        client {
            client()
        }

        server {
            server()
        }

        data {
            data()

            programArguments.addAll("--mod", "appmek", "--all", "--output", file("src/generated/resources/").absolutePath, "--existing", file("src/main/resources").absolutePath)
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'fml.earlyprogresswindow', 'false'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        appmek {
            sourceSet(sourceSets.main)
        }
    }
}

tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            version: project.version,
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
// Include the output of "generateModMetadata" as an input directory for the build
// this works with both building through Gradle and the IDE.
sourceSets.main.resources.srcDir generateModMetadata
legacyForge.ideSyncTask generateModMetadata

/////////////
// Spotless
spotless {
    java {
        target("src/main/java/**/*.java")

        endWithNewline()
        leadingTabsToSpaces()
        removeUnusedImports()
        toggleOffOn()
        eclipse().configFile("codeformat/codeformat.xml")
        importOrderFile("codeformat/ae2.importorder")
    }

    format("json") {
        target("src/*/resources/**/*.json")
        targetExclude("src/generated/resources/**")
        prettier().config(parser: "json")
    }
}

////////////////
// mod-publish-plugin
publishMods {
    displayName = project.version
    changelog = "View changelog at [the release page](https://github.com/AppliedEnergistics/Applied-Mekanistics/releases/tag/${project.version})"

    if (project.version.contains("alpha")) {
        type = ALPHA
    } else if (project.version.contains("beta")) {
        type = BETA
    } else {
        type = STABLE
    }

    file = reobfJar.archiveFile
    modLoaders.add("forge")

    curseforge {
        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
        projectId = "574300"
        minecraftVersions.add(minecraft_version)
        requires("applied-energistics-2")
        requires("mekanism")
    }

    modrinth {
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        projectId = "IiATswDj"
        minecraftVersions.add(minecraft_version)
        requires("ae2")
        requires("mekanism")
    }
}
