minecraft_version=1.20.1
forge_version=47.4.10
ae2_version=15.4.10
guideme_version=20.1.7
mekanism_version=10.4.16.80
jei_version=15.20.0.121
emi_version=1.1.22+1.20.1
jade_id=6855440

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
